app/api/v1/home/models.py
from sqlalchemy import inspect
from app.extensions import db

# write your models here


class User(db.Model):
    """User model."""
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    role = db.Column(db.String(120), nullable=False, default='user')

    def __init__(self, username=None, email=None, role=None):
        """User constructor."""
        super().__init__()
        self.username = username
        self.email = email
        self.role = role

    def serialize_record(self):
        return {c.key: getattr(self, c.key)
                for c in inspect(self).mapper.column_attrs}

    def serialize_records(records):
        return [record.serialize_record() for record in records]

    def __repr__(self):
        """Print the user object."""
        return "<User '{}'>".format(self.firstname)

app/__init__.py
from flask import Flask
from instance.config import app_config
from app.extensions import db, cors
from utils.utils import load_env_file
from app.celery import make_celery
from arrotechtools import ErrorHandler


def create_app(config_name='development'):
    """Create and set up the application."""
    app = Flask(__name__, instance_relative_config=True)

    app.config.from_object(app_config[config_name])
    app.config.from_pyfile('config.py')
    cors.init_app(app)
    make_celery(app)

    from app.api.v1.home import models  # noqa

    db.init_app(app)

    from app.api.v1 import blueprint_v1  # noqa

    app.register_blueprint(blueprint_v1, url_prefix='/api/v1/')
    app.register_error_handler(400, ErrorHandler.bad_request)
    app.register_error_handler(404, ErrorHandler.page_not_found)
    app.register_error_handler(405, ErrorHandler.method_not_allowed)
    app.register_error_handler(500, ErrorHandler.internal_server_error)

    load_env_file()

    return app

app/api/v1/__init__.py
from flask import Blueprint
"""Group related views."""

blueprint_v1 = Blueprint('blueprint_v1', __name__, template_folder='../../../templates', static_folder='../../../static')

from app.api.v1.home import views # noqa

app/api/v1/home/views.py
import json
from flask import render_template, request, jsonify
from app.api.v1.home.models import User
from app.extensions import db
from arrotechtools import Serializer, Validate, ErrorHandler
from sqlalchemy import exc

from app.api.v1 import blueprint_v1
# write your views here


@blueprint_v1.route('/home', methods=['GET'])
def index():
    """Home page."""
    return render_template('home/index.html')


@blueprint_v1.route('/users', methods=['GET', 'POST'])
def users():
    """Add user."""
    try:
        errors = Validate.request_body_keys(request, ["username", "email"])
        if errors:
            return ErrorHandler.raise_error(message="Invalid {} key".format(', '.join(errors)),  # noqa
                                            status_code=400)
        if request.method == 'GET':
            users = fetch_all(User)
            return Serializer.serialize(response=User.serialize_records(users),
                                        message="Successfully retrieved.",
                                        status_code=200
                                        )
        record = add_record("username", "email")
        if not Validate.email(record[1]):
            return ErrorHandler.raise_error(message="Invalid email",
                                            status_code=400)
        user = User(record[0], record[1])
        db.session.add(user)
        db.session.commit()
        return Serializer.serialize(response=user.serialize_record(),
                                    message="Account successfully created.",
                                    status_code=201)
    except Exception as e:
        return ErrorHandler.raise_error(message=str(e),
                                        status_code=400)


@blueprint_v1.route('/user/<int:id>', methods=['GET', 'DELETE', 'PUT', 'PATCH'])  # noqa
def get_user(id):
    """Get a specific user by id."""
    try:
        user = fetch_one(User, id)

        if request.method == 'GET':
            return Serializer.serialize(
                response=user.serialize_record(),
                message="Successfully retrieved.",
                status_code=200)
        elif request.method == 'DELETE':
            db.session.delete(user)
            db.session.commit()
            return Serializer.on_success(status_code=204,
                                         message="Account deleted")
        elif request.method == 'PUT':
            record = update_record(User, id, "username", "email")
            return Serializer.serialize(response=record.serialize_record(),
                                        message="Account successfully updated.",  # noqa
                                        status_code=200)
        elif request.method == 'PATCH':
            record = update_record(User, id, "username")
            return Serializer.serialize(response=record.serialize_record(),
                                        message="Account successfully updated.",  # noqa
                                        status_code=200)
    except Exception:
        return ErrorHandler.raise_error(message="Resource not found",
                                        status_code=404)


def add_record(*args):
    """Add a record."""
    data = request.get_json()
    details = []
    for arg in args:
        details.append(data[arg])
    return details


def update_record(model, id, *args):
    """Updates a record."""
    record = fetch_one(model, id)
    data = request.get_json()
    for arg in args:
        setattr(record, arg, data[arg])
    db.session.commit()
    return record


def fetch_all(model):
    """Fetches all records."""
    records = model.query.all()
    return records


def fetch_one(model, id):
    """Fetches one record."""
    record = model.query.filter_by(id=id).first()
    return record

app/api/v1/views/views.py
from arrotechtools import Serializer

from app.api.v1 import blueprint_v1

# write your views here


@blueprint_v1.route('/')
def index():
    """Home page endpoint."""

    response = {
        "msg": "Welcome to Flask API"
    }

    return Serializer.serialize(response, 200, "OK")

templates/home/index.html
{% block title %}
Flask API Starter Template
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('blueprint_v1.index') }}">Flask API</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('blueprint_v1.index') }}">Home <span
                        class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-info my-2 my-sm-0 text-light" type="submit">Search</button>
        </form>
    </div>
</nav>
{% endblock %}

{% block content %}
<div class="container">
    <div class="alert alert-primary mt-5" role="alert">
        Welcome to Flask API Starter Template
    </div>
    <div class="row">
        <div class="col-lg-4 mt-2">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">Bootstrap</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Flask Bootstrap</h6>
                    <p class="card-text">The template uses Flask-Boostrap for styling. You can familiarize yourself with
                        the
                        extension to take advantage of boostrap classes, components e.t.c.</p>
                    <a href="https://pythonhosted.org/Flask-Bootstrap/basic-usage.html" class="card-link">Get Started
                        with
                        Flask-Boostrap</a>
                </div>
            </div>
        </div>
        <div class="col-lg-8 mt-2">
            <!-- <p class="lead">
                You can customize this template theme to be your landing page. <span class="h3">💣</span>
            </p> -->
            <ul class="list-group">
                <li class="list-group-item"><h4>These are some of the boostrap classes.</h4></li>
                <li class="list-group-item bg-dark text-light">Dapibus ac facilisis in</li>
                <li class="list-group-item bg-warning">Morbi leo risus</li>
                <li class="list-group-item bg-success">Porta ac consectetur ac</li>
                <li class="list-group-item bg-danger text-light">Vestibulum at eros</li>
            </ul>
        </div>

    </div>
</div>
{% endblock %}